[package]
name = "maketemp"
version = "0.1.0"
edition = "2021"
description = "Create temporary directory and files."
license = "MIT"
repository = "https://github.com/yokoyup/maketemp-rs.git"

[dependencies]
